version: "3.8"
services:
  minio:
    image: minio/minio:latest
    container_name: boxops-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: {{M_USER}}
      MINIO_ROOT_PASSWORD: {{M_PASS}}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - boxops-network

networks:
  boxops-network:
    external: true
volumes:
  minio-data:
