version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: boxops-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: {{DB_USER}}
      POSTGRES_PASSWORD: {{DB_PASS}}
      POSTGRES_DB: {{DB_NAME}}
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - boxops-network

networks:
  boxops-network:
    external: true
volumes:
  pg-data:
